### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by lanaherman** [lanaherman/APPR-2018-19#2]
Pozdravljeni!

Ali je spodnji zemljevid narejen dovolj dobro?

Lep pozdrav,
Lana Herman

![Rplot01](https://user-images.githubusercontent.com/45061277/66768199-4f16e280-eeb2-11e9-90f6-6128c9dc9878.png)

**Comment by MarvinHerzog** [comment]
Zdravo,

konceptualno izgleda v redu, tudi nobena regija ne manjka. Problem je trganje večkotnikov. 

`ggplot`-u moraš povedati v katerem vrstnem redu mora risati vozlišča večkotnikov. To lahko narediš tako, da v klic `ggplot` funkcije dodaš `group` parameter na tisti stolpec, ki v `data.frame`-u tvojega zemljevida predstavlja pravo zaporedje. V primeru iz tvoje prejšnje kode je to stolpec z imenom group:

```
ggplot() + geom_polygon(data=left_join(zemljevid, povprecja, by=c("OB_UIME"="obcina")),
                        aes(x=long, y=lat, group=group, fill=povprecje))
```

V primeru, da to ne zaleže, preveri ali so v kakih prejšnjih korakih kakšni `merge`-i ali `join`-i pokvarili originalno zaporedje vozlišč. Najlažje, da poskusiš uporabljati `left_join` na originalno tabelo zemljevida, saj boš s tem ohranila njegovo urejenost.

Še nekaj virov:

https://gis.stackexchange.com/questions/165974/r-fortify-causing-polygons-to-tear
https://gis.stackexchange.com/questions/37204/what-is-the-cause-of-tearing-of-polygons-artifacts-using-r-ggplot-and-geom
https://gis.stackexchange.com/questions/140095/ggplot2-plots-polygons-with-wrong-topologies

Če ne bo šlo, pa lahko commitaš projekt in bomo pogledali kje je težava.

**Comment by lanaherman** [comment]
Pozdravljeni!

Hvala za odgovor. Napako naredi pri merge-ih. Kolikor sem gledala, se imena občin ujemajo (oz. problem pri nekaterih je bil, da je za in pred pomišljaji presledek, to sem odpravila s pomočjo gsub(" ", "", ...)), tako da ne vem kje bi lahko bila napaka. Kodo sem commitala.

**Comment by lanaherman** [comment]
Pozdravljeni!

Sedaj je slika cela. Hvala za pomoč.
![Rplot02](https://user-images.githubusercontent.com/45061277/66858344-5f4dc100-ef89-11e9-9a18-4de8b4f06c87.png)
