### ISSUE TITLE
Tortni grafikon

### ISSUE THREAD

**Issue by lanaherman** [lanaherman/APPR-2018-19#3]
Pozdravljeni!

V razdelku HISTOGRAM PRIMERJAVA VRSTE ZIVINE V EKO IN NE EKO v mapi uvoz želim narediti tortni grafikon tako, da so procenti posameznih spremenljivk zunaj grafikona (če niso se namreč številk ne vidi, kot je opazno pod # GRDO IZPISE). Pod # NEUSPELI POIZKUS mi izpiše samo za eno spremenljivko. Kako bi se dalo to popraviti?

Lep pozdrav,
Lana Herman.

**Comment by jaanos** [comment]
Najprej bi opozoril na kodo iz vzorca, ki je ostala na začetku `uvoz.r` - če je ne potrebuješ, jo lahko pobrišeš. Za branje datotek raje uporabi funkcijo `read_delm` (s podčrtajem!) iz knjižnice `readr` - pri tem pa obvezno navedi kodiranje znakov, npr.
```R
Tabela4 <- read_delim("podatki/Pridelava ekoloskih rastlinskih pridelkov.csv", delim=";",
                      na=c("", " ", "...", "-"),
                      locale=locale(encoding="Windows-1250", decimal_mark="."))
```
Načeloma bi lahko uporabljala tudi `read_csv` ali `read_csv2`, a pri teh ni mogoče spreminjati ločila decimalk. V samih podatkih števil ne zaokrožuj - po potrebi lahko to narediš šele pri prikazu.

Za tortni diagram si lahko pomagaš s funkcijo `geom_arc_bar` iz knjižnice `ggforce` (glej tudi https://stackoverflow.com/questions/16184188/ggplot-facet-piechart-placing-text-in-the-middle-of-pie-chart-slices):
```R
library(ggforce)
br <- ggplot(r %>% arrange(desc(Zivina)) %>%
               mutate(end_angle=2*pi*cumsum(stevilo)/sum(r$stevilo),
                      start_angle=lag(end_angle, default = 0),
                      mid_angle=0.5*(start_angle + end_angle),
                      hjust=ifelse(mid_angle>pi, 1, 0),
                      vjust=ifelse(mid_angle<pi/2 | mid_angle>3*pi/2, 0, 1))) +
  geom_arc_bar(aes(x0=0, y0=0, r0=0, r=1,
                   start=start_angle, end=end_angle, fill=Zivina))
tortni_ne_eko_ziv <- br + coord_fixed() +
  scale_fill_brewer("Vrsta zivine", palette="Dark2") + theme_void() +
  geom_text(aes(label=paste0(round(as.numeric(label1)), "%"),
                x=1.1*sin(mid_angle), y=1.1*cos(mid_angle), hjust=hjust, vjust=vjust)) +
  labs(x=NULL, y=NULL, fill=NULL, title="Struktura ekoloske zivine")
```
Natančen položaj oznak določa koeficient 1.1 pri parametrih `x` in `y` pri `geom_text`. Svetoval bi sicer, da izpustiš oznake *0%*.

**Comment by lanaherman** [comment]
Hvala za odgovor!
Kako pa lahko izpustim 0%? Poskusila sem z round(as.numeric(r$label1)[as.numeric(r$label1)>1]) pogojem ampak mi vrne napako..

**Comment by jaanos** [comment]
Lahko narediš nekaj takega:
```R
label=label1 %>% as.numeric() %>% round() %>% ifelse(paste0(., "%"), "")
```
Tukaj je izkoriščeno dejstvo, da `ifelse` (in na splošno stavek `if`) razume ničle kot `FALSE`, ostale vrednosti pa kot `TRUE`, tako da se v slednjem primeru doda še znak *%* (pika pomeni trenutni vhod, torej zaokrožena števila), sicer se pa uporabi prazen niz.

Mimogrede, datoteke `cene.csv` nimaš na repozitoriju, zato zadnji uvoz ne deluje.

**Comment by lanaherman** [comment]
Hvala za pomoč.
Sem naložila.
