### ISSUE TITLE
Dokončan projetk

### ISSUE THREAD

**Issue by lanaherman** [lanaherman/APPR-2018-19#4]
Pozdravljeni!

Projekt zaključujem, zato bi vas prosila, če ga dodate na repozitorij za zagovore, oziroma ali je potrebno še kaj popraviti?

Lep pozdrav,
Lana Herman.

**Comment by jaanos** [comment]
Poročila trenutno pri meni ne prevede - problem se pojavi zaradi kodiranja znakov v razpredelnici `Tabela7`. Glede na to, da se tukaj za ločila decimalk uporabljajo vejice, lahko za uvoz uporabiš kar `read_csv2`, pri čemer izpustiš prvo vrstico z letnicami, ki jih bo treba nato na roko nastaviti kot imena stolpcev:
```R
Tabela7 <- read_csv2("podatki/cene.csv", na=c("", " ", "...", "-"), skip=1,
                     locale=locale(encoding="Windows-1250"))
colnames(Tabela7) <- c("IZDELEK", 2000:2018)
```
Tako se bodo tudi števila pravilno uvozila. Preostanek obdelave (pretvorba v *tidy data*) lahko potem ostane nespremenjen.

Opozoril bi še na odvečne podatke v razpredelnici `Tabela4` - za naziv `NA` se pojavijo podatki z letnicami (najlažje se jih znebiš tako, da pri `read_delim` dodaš še parameter `skip=1`). Na koncu poročila se izpiše še `***` - zadnjo vrstico lahko kar odstraniš, če pa želiš prikazati vodoravno črto na koncu, pred zvezdice postavi še prazno vrstico.

Da se znebiš sporočila pri uvozu zemljevida, lahko v glavo bloka kode, kjer kličeš `vizualizacija.r`, dodaš parameter `results='hide'`. Zemljevid se izriše nekoliko nenavadno (nekatere občine so obarvane drugače od okolice) - glede na to, da imaš podatke po statističnih regijah in ne po občinah, svetujem, da raje uporabiš ustrezen zemljevid, npr. https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_SVN_shp.zip, zemljevid `gadm36_SVN_1` (pri uvozu parameter `pot.zemljevida` izpusti, za kodiranje znakov pa uporabi `UTF-8`).

Naslednji graf imenuješ histogram, a gre za navaden stolpčni graf (pri histogramu je na eni osi vrednost spremenljivke, na drugi pa njega pogostost - tukaj enostavno prikazuješ vrednost ene spremenljivke v odvisnosti od druge). Komentiral bi še zadnji graf - ker je število jajc veliko večje od števila perutnine, se slednje na grafu vidi kot ravna črta. Zato bo bolje, če prikažeš dva grafa z različnimi skalami - to lahko dosežeš tako, da grafu prišteješ še `facet_grid(izdelek~., scales="free_y")` (legendo lahko v tem primeru odstraniš). Seveda pa tukaj ne gre za korelacijo, ampak le prikaz gibanja skozi leta. Za prikaz korelacije bi morala vsako od teh vrednosti prikazati na svoji osi.

Pogrešam sicer kakšno naprednejšo analizo. Iz podatkov, ki jih imaš, bi se zagotovo dalo zgraditi kak model in na njegovi podlagi napovedati gibanje katere od spremenljivk v prihodnosti.

**Comment by lanaherman** [comment]
Pozdravljeni!

Hvala za vaše pripombe. Zemljevid, ki ste ga predlagali mi zmeraj vrača napako "Cannot open data source". Na internetu nisem našla rešitve, tako da sem kodo pustila v komentarju.
Ostale pripombe sem upoštevala in dodala še shiny. Če je še kaj za popravit mi prosim sporočite.

Hvala in lep pozdrav.

**Comment by jaanos** [comment]
Poročilo zdaj deluje, tako da sem dodal povezavo na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat kaj spreminjala, mi javi, da posodobim povezavo.

Da bo zemljevid deloval, bo potrebno popraviti sledečo vrstico v `uvozi.zemljevid.r`:
https://github.com/lanaherman/APPR-2018-19/blob/b08c7ee5e5340c0e644582f612074d97ecb241eb/lib/uvozi.zemljevid.r#L53
Namesto `pot` uporabi spremenljivko `shp`. Seveda bo pri uporabi tega zemljevida potrebno spremeniti imena stolpcev, po katerih združuješ.

**Comment by lanaherman** [comment]
Sem popravila še zemljevid.
Najlepša hvala za vso pomoč!

Lep pozdrav.

**Comment by jaanos** [comment]
V redu, bom posodobil povezavo.
